### ISSUE TITLE
Bot issue

### ISSUE THREAD

**Issue by AGidProF** [TheGetsuzoThunder/znxinvasion#1]
Setiap make bug catalog entah kenapa bit nya error keluar sendiri 

kalo bisa di fix :)

-ttd AkuGanteng

**Comment by TheGetsuzoThunder** [comment]
> Setiap make bug catalog entah kenapa bit nya error keluar sendiri
> 
> kalo bisa di fix :)
> 
> -ttd AkuGanteng

Chat wa gan
wa.me/62853338317160
